"""FastAPI composition-root surfaces for the Governed LLM Gateway."""

from .application import create_gateway_app
from .application_bootstrap import (
    GovernedApplicationArtifacts,
    GovernedApplicationBootstrapPaths,
    bootstrap_governed_application_services,
    load_governed_application_artifacts,
    materialize_governed_application_services,
    validate_operational_evidence_registry,
)
from .client_auth import (
    EnvironmentGatewayClientSecretResolver,
    GatewayClientAuthBinding,
    GatewayClientAuthenticationConfigurationError,
    GatewayClientAuthorizationError,
    GatewayClientIdentity,
    GatewayClientSecretResolutionError,
    GatewayClientSecretResolver,
    StaticGatewayClientContextResolver,
    build_static_gateway_client_context_resolver,
)
from .client_auth_json import (
    DuplicateGatewayClientAuthKeyError,
    GatewayClientAuthDocument,
    GatewayClientAuthDocumentError,
    load_gateway_client_auth_document,
    load_gateway_client_auth_document_text,
)
from .complexity_evidence import (
    ComplexityAssessmentExplainModel,
    ComplexityExplainModel,
    ComplexityHttpEvidenceInvariantViolation,
    ComplexityNarrowingExplainModel,
    complexity_evidence_from_decision,
)
from .complexity_generate import ComplexityGenerateCoordinator
from .deployment_activation import GovernedDeploymentSettings, activate_governed_deployment
from .gateway_runtime_bootstrap import (
    GatewayRuntimeBootstrapBundle,
    GatewayRuntimeBootstrapPaths,
    bootstrap_gateway_runtime,
)
from .operations_access import (
    GatewayClientIdentityAuthenticator,
    OperationsReadAccessConfigurationError,
    OperationsReadAccessPolicy,
    OperationsReadAccessService,
    OperationsReadAuthorizationError,
)
from .operations_access_json import (
    DuplicateOperationsReadAccessKeyError,
    OperationsReadAccessDocument,
    OperationsReadAccessDocumentError,
    load_operations_read_access_document,
    load_operations_read_access_document_text,
    validate_operations_access_client_auth,
)
from .operations_http import (
    OperationsEvidenceOverviewModel,
    OperationsHealthOverviewModel,
    OperationsHttpCompositionError,
    OperationsOverviewResponseModel,
    OperationsRankingOverviewModel,
    OperationsReadAuthorizer,
    OperationsRegistryOverviewModel,
    OperationsSnapshotReader,
    attach_operations_routes,
)
from .operations_snapshot import DeploymentOperationsSnapshotReader
from .policy_router_bootstrap import (
    PolicyRouterClientAuthMismatchError,
    PolicyRouterRuntimeBootstrapBundle,
    PolicyRouterRuntimeBootstrapPaths,
    bootstrap_policy_router_runtime,
    validate_policy_router_client_auth,
)
from .process_bootstrap import (
    GovernedProcessArtifacts,
    GovernedProcessBootstrapPaths,
    GovernedProcessRuntimeBundle,
    bootstrap_governed_process_runtime,
    load_governed_process_artifacts,
    materialize_governed_process_runtime,
)
from .process_health import (
    ProcessHealthCompositionError,
    ProcessLiveResponse,
    ProcessReadyResponse,
    attach_process_health_routes,
)
from .provider_bootstrap import (
    ProviderRuntimeBootstrapBundle,
    ProviderRuntimeBootstrapPaths,
    bootstrap_provider_runtime,
)
from .route_explain import (
    ClientAuthenticationError,
    ComplexityRouteExplainCoordinator,
    ComplexityRouteExplainResponseModel,
    EffectiveContextResolver,
    RouteExplainCoordinator,
    RouteExplainRequestModel,
    RouteExplainResponseModel,
    create_app,
)
from .server import (
    GovernedServerSettings,
    ServerRunner,
    UvicornServerRunner,
    parse_server_args,
    run_governed_server,
)
from .service_composition import (
    GovernedGatewayServices,
    GovernedServiceCompositionError,
    compose_governed_gateway_services,
    validate_governed_routing_inputs,
)
from .stream_generate import (
    GenerateCoordinator,
    GenerateRequestModel,
    PreparedStreamingExecution,
    attach_generate_route,
)

__all__ = [
    "ClientAuthenticationError",
    "ComplexityAssessmentExplainModel",
    "ComplexityExplainModel",
    "ComplexityGenerateCoordinator",
    "ComplexityHttpEvidenceInvariantViolation",
    "ComplexityNarrowingExplainModel",
    "ComplexityRouteExplainCoordinator",
    "ComplexityRouteExplainResponseModel",
    "DeploymentOperationsSnapshotReader",
    "DuplicateGatewayClientAuthKeyError",
    "DuplicateOperationsReadAccessKeyError",
    "EffectiveContextResolver",
    "EnvironmentGatewayClientSecretResolver",
    "GatewayClientAuthBinding",
    "GatewayClientAuthDocument",
    "GatewayClientAuthDocumentError",
    "GatewayClientAuthenticationConfigurationError",
    "GatewayClientAuthorizationError",
    "GatewayClientIdentity",
    "GatewayClientIdentityAuthenticator",
    "GatewayClientSecretResolutionError",
    "GatewayClientSecretResolver",
    "GatewayRuntimeBootstrapBundle",
    "GatewayRuntimeBootstrapPaths",
    "GenerateCoordinator",
    "GenerateRequestModel",
    "GovernedApplicationArtifacts",
    "GovernedApplicationBootstrapPaths",
    "GovernedDeploymentSettings",
    "GovernedGatewayServices",
    "GovernedProcessArtifacts",
    "GovernedProcessBootstrapPaths",
    "GovernedProcessRuntimeBundle",
    "GovernedServerSettings",
    "GovernedServiceCompositionError",
    "OperationsEvidenceOverviewModel",
    "OperationsHealthOverviewModel",
    "OperationsHttpCompositionError",
    "OperationsOverviewResponseModel",
    "OperationsRankingOverviewModel",
    "OperationsReadAccessConfigurationError",
    "OperationsReadAccessDocument",
    "OperationsReadAccessDocumentError",
    "OperationsReadAccessPolicy",
    "OperationsReadAccessService",
    "OperationsReadAuthorizationError",
    "OperationsReadAuthorizer",
    "OperationsRegistryOverviewModel",
    "OperationsSnapshotReader",
    "PolicyRouterClientAuthMismatchError",
    "PolicyRouterRuntimeBootstrapBundle",
    "PolicyRouterRuntimeBootstrapPaths",
    "PreparedStreamingExecution",
    "ProcessHealthCompositionError",
    "ProcessLiveResponse",
    "ProcessReadyResponse",
    "ProviderRuntimeBootstrapBundle",
    "ProviderRuntimeBootstrapPaths",
    "RouteExplainCoordinator",
    "RouteExplainRequestModel",
    "RouteExplainResponseModel",
    "ServerRunner",
    "StaticGatewayClientContextResolver",
    "UvicornServerRunner",
    "activate_governed_deployment",
    "attach_generate_route",
    "attach_operations_routes",
    "attach_process_health_routes",
    "bootstrap_gateway_runtime",
    "bootstrap_governed_application_services",
    "bootstrap_governed_process_runtime",
    "bootstrap_policy_router_runtime",
    "bootstrap_provider_runtime",
    "build_static_gateway_client_context_resolver",
    "complexity_evidence_from_decision",
    "compose_governed_gateway_services",
    "create_app",
    "create_gateway_app",
    "load_gateway_client_auth_document",
    "load_gateway_client_auth_document_text",
    "load_governed_application_artifacts",
    "load_governed_process_artifacts",
    "load_operations_read_access_document",
    "load_operations_read_access_document_text",
    "materialize_governed_application_services",
    "materialize_governed_process_runtime",
    "parse_server_args",
    "run_governed_server",
    "validate_governed_routing_inputs",
    "validate_operational_evidence_registry",
    "validate_operations_access_client_auth",
    "validate_policy_router_client_auth",
]
